# Generated by Django 2.2 on 2019-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(default='default.jpg', upload_to='thumbnail/'),
        ),
    ]
