# Generated by Django 2.0.1 on 2019-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190620_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(default='default.jpeg', upload_to='thumbnail/'),
        ),
    ]
